/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 10.4.6-MariaDB : Database - djemfcst_v2
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`djemfcst_v2` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `djemfcst_v2`;

/*Table structure for table `finance_transaction_categories` */

DROP TABLE IF EXISTS `finance_transaction_categories`;

CREATE TABLE `finance_transaction_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_income` tinyint(1) DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT 0,
  `trans_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `payment_mode` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `account_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=COMPACT;

/*Data for the table `finance_transaction_categories` */

insert  into `finance_transaction_categories`(`id`,`name`,`description`,`is_income`,`deleted`,`trans_type`,`payment_mode`,`account_code`) values (1,'BOOK SALES','BOOK SALES',1,0,'FEES','ADMISSION',NULL),(2,'ID CARD SALES','ID CARD SALES',1,0,'FEES','ADMISSION',NULL),(3,'CASH/CHECK VOUCHER','CASH/CHECK VOUCHER',0,0,'FEES','VOUCHER',NULL),(4,'FinanceFee','FinanceFee',1,0,'FEES','ADMISSION',NULL),(5,'TRANSCRIPT OF RECORDS (TOR)','TRANSCRIPT OF RECORDS (TOR)',1,0,'FORM','COLLECTION','4014'),(6,'GOOD MORAL','GOOD MORAL',1,0,'FORM','COLLECTION',NULL),(7,'FORM 137','FORM 137',1,0,'FORM','COLLECTION',NULL),(8,'CERTIFICATION OF RATING','CERTIFICATION OF RATING',1,0,'FORM','COLLECTION',NULL),(9,'HONORABLE DISMISSAL','HONORABLE DISMISSAL',1,0,'FORM','COLLECTION',NULL),(10,'STUDENT HANDBOOK','STUDENT HANDBOOK',1,0,'FORM','COLLECTION',NULL),(11,'OJT JOURNAL','OJT JOURNAL',1,0,'FORM','COLLECTION',NULL),(12,'LIBRARY CARD','LIBRARY CARD',1,0,'FORM','COLLECTION',NULL),(13,'DIPLOMA','DIPLOMA',1,0,'FORM','COLLECTION',NULL),(14,'OFFICE PRODUCTIVITY TOOLS','OFFICE PRODUCTIVITY TOOLS',1,0,'GRADUATING STUDENTS','COLLECTION',NULL),(15,'DEPLOYMENT FEE','DEPLOYMENT FEE',1,0,'GRADUATING STUDENTS','COLLECTION',NULL),(16,'REVALIDA','REVALIDA',1,0,'GRADUATING STUDENTS','COLLECTION',NULL),(17,'STUDENT TEACHER ORIENTATION','STUDENT TEACHER ORIENTATION',1,0,'GRADUATING STUDENTS','COLLECTION',NULL),(18,'CTE','CTE',1,0,'AFFILIATION FEE','COLLECTION',NULL),(19,'AB','AB',1,0,'AFFILIATION FEE','COLLECTION',NULL),(20,'BSIT','BSIT',1,0,'AFFILIATION FEE','COLLECTION',NULL),(21,'BSBA','BSBA',1,0,'AFFILIATION FEE','COLLECTION',NULL),(22,'HMTM','HMTM',1,0,'AFFILIATION FEE','COLLECTION',NULL),(23,'BSCRIM','BSCRIM',1,0,'AFFILIATION FEE','COLLECTION',NULL),(24,'BSFM','BSFM',1,1,'AFFILIATION FEE','COLLECTION','4018'),(25,'BSFM','BSFM',1,1,'AFFILIATION FEE','COLLECTION','4018'),(26,'BSFM','',1,1,'AFFILIATION FEE','COLLECTION','4018');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
